
---
wordConfig:
  lucky-word: Ashrith 
  my-lucky: AADHYA 

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/profile
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

#spring.datasource.url=jdbc:mysql://localhost:3306/profile
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
#spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto = update
